#!/bin/sh /etc/rc.common
# ePortal 自动认证守护服务（OpenWrt procd）
# 由 install.sh 安装到 /etc/init.d/eportal
# 管理: /etc/init.d/eportal start|stop|restart|enable|disable

START=99
STOP=15

PROG=/usr/bin/eportal-watchdog.sh

start_service() {
    procd_open_instance
    procd_set_param command /bin/bash "$PROG"
    procd_set_param respawn 3600 5 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}
